# Generated by Django 3.0.7 on 2020-07-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.CharField(default='', max_length=254)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('currency', models.CharField(default='', max_length=254)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
