# Generated by Django 3.0.7 on 2020-07-04 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('startDate', models.DateField(default=datetime.datetime(2020, 7, 1, 20, 43, 8, 350388))),
                ('endDate', models.DateField(default=datetime.datetime(2020, 7, 1, 20, 43, 8, 350388))),
                ('startBalance', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('endBalance', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('totalIn', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('totalOut', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('freeCash', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='', max_length=254)),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
            },
        ),
    ]
