# Generated by Django 3.0.7 on 2020-07-04 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='endDate',
            field=models.DateField(default=31),
        ),
        migrations.AlterField(
            model_name='period',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2020, 7, 1, 20, 51, 27, 405724)),
        ),
    ]
