# Generated by Django 3.0.7 on 2020-07-09 08:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20200704_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.AlterField(
            model_name='period',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2020, 7, 31, 9, 13, 56, 712886)),
        ),
        migrations.AlterField(
            model_name='period',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2020, 7, 1, 9, 13, 56, 712886)),
        ),
        migrations.CreateModel(
            name='Transcation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Planned', 'Planned')], default='', max_length=254)),
                ('notes', models.CharField(default='', max_length=254)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Category')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Period')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Type')),
            ],
            options={
                'verbose_name': 'Transcation',
                'verbose_name_plural': 'Transcations',
            },
        ),
    ]
